"""prices_currency_images_lastcost

Revision ID: 58274d5910dc
Revises: e7e893cfe315
Create Date: 2026-05-06 19:23:24.040047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '58274d5910dc'
down_revision: Union[str, None] = 'e7e893cfe315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL columns are added with a server_default so existing rows
    # get a valid value, then the default is dropped — the application
    # layer stays the source of truth for new-row defaults.
    op.add_column('items', sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    op.add_column('items', sa.Column('last_unit_cost', sa.Float(), nullable=True))

    op.add_column('po_lines', sa.Column('unit_price', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('po_lines', 'unit_price', server_default=None)

    op.add_column(
        'purchase_orders',
        sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default='USD'),
    )
    op.alter_column('purchase_orders', 'currency', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'currency')
    op.drop_column('po_lines', 'unit_price')
    op.drop_column('items', 'last_unit_cost')
    op.drop_column('items', 'image_path')
    # ### end Alembic commands ###
