"""initial schema

Revision ID: e7e893cfe315
Revises: 
Create Date: 2026-05-06 17:54:41.719175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = 'e7e893cfe315'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoho_item_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=False),
    sa.Column('sku_code', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('daily_usage_rate', sa.Float(), nullable=False),
    sa.Column('reorder_point', sa.Float(), nullable=False),
    sa.Column('reorder_point_locked', sa.Boolean(), nullable=False),
    sa.Column('critical_point', sa.Float(), nullable=False),
    sa.Column('sea_lead_days', sa.Integer(), nullable=False),
    sa.Column('express_lead_days', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_sku_code'), 'items', ['sku_code'], unique=False)
    op.create_index(op.f('ix_items_zoho_item_id'), 'items', ['zoho_item_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'AGENT', 'DESIGN', 'RECEIVING', name='role'), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('tg_pending_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tg_pending_po_id', sa.Integer(), nullable=True),
    sa.Column('tg_pending_set_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=False)
    op.create_table('zoho_mirror',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zoho_purchaseorder_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('purchaseorder_number', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('delivery_date', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoho_mirror_zoho_purchaseorder_id'), 'zoho_mirror', ['zoho_purchaseorder_id'], unique=True)
    op.create_table('app_settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'DESIGN_REVIEW', 'DESIGN_REJECTED', 'DESIGN_APPROVED', 'PI_RECEIVED', 'PI_APPROVED', 'PRODUCTION', 'SHIPPED', 'RECEIVED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('urgency', sa.Enum('NORMAL', 'HIGH', 'CRITICAL', name='urgency'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('zoho_po_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('push_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('push_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('push_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('last_production_reminder_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_zoho_po_id'), 'purchase_orders', ['zoho_po_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('po_mirrored', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_started_at'), 'sync_runs', ['started_at'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('PI', 'ARTWORK', 'OTHER', name='attachmentkind'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_po_id'), 'attachments', ['po_id'], unique=False)
    op.create_table('po_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_events_created_at'), 'po_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_po_events_po_id'), 'po_events', ['po_id'], unique=False)
    op.create_table('po_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('target_arrival', sa.Date(), nullable=True),
    sa.Column('received_quantity', sa.Float(), nullable=False),
    sa.Column('line_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_lines_item_id'), 'po_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_po_lines_po_id'), 'po_lines', ['po_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('EXPRESS', 'SEA', name='shipmethod'), nullable=False),
    sa.Column('status', sa.Enum('IN_TRANSIT', 'RECEIVED', 'PARTIAL', name='shipstatus'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('received_quantity', sa.Float(), nullable=True),
    sa.Column('shipped_date', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discrepancy_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_po_id'), 'shipments', ['po_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_po_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_po_lines_po_id'), table_name='po_lines')
    op.drop_index(op.f('ix_po_lines_item_id'), table_name='po_lines')
    op.drop_table('po_lines')
    op.drop_index(op.f('ix_po_events_po_id'), table_name='po_events')
    op.drop_index(op.f('ix_po_events_created_at'), table_name='po_events')
    op.drop_table('po_events')
    op.drop_index(op.f('ix_attachments_po_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_sync_runs_started_at'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_purchase_orders_zoho_po_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_zoho_mirror_zoho_purchaseorder_id'), table_name='zoho_mirror')
    op.drop_table('zoho_mirror')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_zoho_item_id'), table_name='items')
    op.drop_index(op.f('ix_items_sku_code'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
